services:
  react-nginx-app:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - '8080:80'
    depends_on:
      - db
  nodebackend:
    stdin_open: true
    tty: true
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    volumes:
      - mongodbdata:/data/db
    image: mongo:4.0.4
    ports:
      - '27017:27017'
volumes:
  mongodbdata:
